---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: dbuild
  image: nimlang/nim
  commands:
  - nimble intro
  - nimble dbuild

- name: fbuild
  image: nimlang/nim
  commands:
  - nimble intro
  - nimble fbuild

- name: test
  image: nimlang/nim
  commands:
  - nimble intro
  - nimble test
